services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    mem_limit: 512m
    command: --max-connections=50 --innodb-buffer-pool-size=256M
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: reserve
      MYSQL_USER: ${PROD_DB_USERNAME}
      MYSQL_PASSWORD: ${PROD_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    restart: always
    mem_limit: 128m

  springboot:
    image: ghcr.io/codnjs042/reservation-project-be:latest
    container_name: springboot
    restart: always
    mem_limit: 768m
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
      - redis
    extra_hosts:
      - "api.kcisa.kr:175.125.91.8"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    mem_limit: 64m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../Reservation-Project-FE/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - springboot

volumes:
  mysql_data: