spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

vworld:
  domain: https://yarmspot.store

decorator:
  datasource:
    p6spy:
      enable-logging: false

cors:
  allowed-origin: https://yarmspot.store

swagger:
  enabled: false

logging:
  level:
    root: WARN
    com.example.demo: INFO
    org.hibernate.SQL: ERROR