spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: true

  h2:
    console:
      enabled: false

cors:
  allowed-origin: http://localhost:5173

security:
  h2-console:
    enabled: true

swagger:
  enabled: true

logging:
  level:
    org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j