spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 443
  ssl:
    enabled: true
    certificate: /etc/letsencrypt/live/yarmspot.store/fullchain.pem
    certificate-private-key: /etc/letsencrypt/live/yarmspot.store/privkey.pem

decorator:
  datasource:
    p6spy:
      enable-logging: false

cors:
  allowed-origin: http://15.164.102.201:5173

security:
  h2-console:
    enabled: false

swagger:
  enabled: false

logging:
  level:
    root: WARN
    com.example.demo: INFO
    org.hibernate.SQL: ERROR