server:
  port: 8081
  forward-headers-strategy: framework

spring:
  profiles:
    active: dev
  config:
    import:
      - "optional:classpath:application-private.yml"
      - "optional:classpath:application-private-${spring.profiles.active}.yml"